# Generated by Django 5.0.1 on 2024-01-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
